name: Check generated TOCs

on:
  pull_request:
    paths:
      - "README.md"
      - "docs/BestPractices.md"

permissions:
  contents: read

jobs:
  doctoc:
    name: Doc TOC Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 'lts/*'
      - name: Install doctoc
        run: npm i -g doctoc
      - name: Create README copy and diff with doctoc
        run: cp README.md README.md.tmp &&
          doctoc --title='## Table of Contents' --github README.md &&
          diff -q README.md README.md.tmp
      - name: Create "docs/BestPractices.md" copy and diff with doctoc
        run: cp docs/BestPractices.md docs/BestPractices.md.tmp &&
          doctoc --title='## Table of Contents' --github docs/BestPractices.md &&
          diff -q docs/BestPractices.md docs/BestPractices.md.tmp
