name: Check Alpine CHECKSUM

on:
  pull_request:
    paths:
      - ".github/workflows/missing-checksum.yml"
      - "**/alpine*/Dockerfile"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Count number of Alpine Dockersfiles without CHECKSUM
        run: |
          git grep -n 'CHECKSUM=""' -- '*alpine*/Dockerfile' | sed -E 's/^([^:]+):([^:]+):\s*/::error file=\1,line=\2::Missing pre-built checksum/'
          if [ "${PIPESTATUS[0]}" -eq 0 ]; then
            exit 1
          fi
